apiVersion: v1
kind: Service
metadata:
  name: {{ include "hilltop.fullname" . }}
  labels:
    {{- include "hilltop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "hilltop.selectorLabels" . | nindent 4 }}
