apiVersion: v1
kind: Service
metadata:
  name: {{ include "hilltop.fullname" . }}
  labels:
    {{- include "hilltop.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Ensure this port is within the NodePort range (30000-32767)
  selector:
    {{- include "hilltop.selectorLabels" . | nindent 6 }}
