replicaCount: 3

image:
  repository: hilltopconsultancy/nodejs-app
  tag: v1
  pullPolicy: IfNotPresent

serviceAccount:
  name: "aws-load-balancer-controller"

service:
  type: NodePort
  port: 80
  nodePort: 30080

ingress:
  enabled: true
  certificateArn: "arn:aws:acm:REGION:ACCOUNT_ID:certificate/CERTIFICATE_ID"
  host: "yourdomain.com"
